version: '2.3'
services:
   cam_engine:
      build: CamEngine
      image: project9-toppan_cam_engine
      container_name: project09-cam-engine
      working_dir: /awl/cam_engine
      runtime: nvidia
      volumes:
         - /dev:/dev
         - /tmp/.X11-unix:/tmp/.X11-unix
         - /tmp/.docker.xauth:/tmp/.docker.xauth
         - /etc/localtime:/etc/localtime:ro
         - ./CamEngine/.env:/awl/cam_engine/.env
         - ./outputs/:/awl/cam_engine/outputs
         - ./models:/awl/cam_engine/models
      restart: always
      env_file:
         - CamEngine/.env
      environment:
         - DISPLAY
         - QT_X11_NO_MITSHM=1
      command: >
         /bin/bash -c "source activate proj9 && python main.py"