_BASE_: "Base-RCNN-ShuffleNet-FPN.yaml"
MODEL:
  BACKBONE:
    NAME: "build_shufflenetv2_x1_0_fpn_backbone"
  WEIGHTS: "https://www.dropbox.com/s/raaqxkm993h2kxb/shufflenetv2_x1.0-72ccf27e.pth?dl=1"
  MASK_ON: False
  FPN:
    OUT_CHANNELS: 128
  ROI_HEADS:
    NUM_CLASSES: 1
DATASETS:
  TRAIN: ("cocohandBig_train", "cocohandBig_val", "cocohandBig_test", "oxfordhand_train", "oxfordhand_val", "egohand_train", "egohand_val", "tvhand_train", "tvhand_val")
  TEST: ("egohand_test", "oxfordhand_test", "tvhand_test")
OUTPUT_DIR: "checkpoints_hand/FRCN-ShuffleNetV2-FPNLite-1x"